[WIP] 4.16. Method Syntax (1.9)
rust-lang-ja/the-rust-programming-language-ja pull request #174
Opened 2016-06-25 05:09 UTC by tatsuya6502

- Update the contents.
- Change the comment style to use the same style to other pages.

2017-03-07 13:24 UTC, tatsuya6502 commented
@KeenS レビューをお願いします。

訳文を手直ししています。25行目の leading question の訳や、306行目の to enforce の訳など、意味を変えた所もありますので、全体を通して訳をレビューしていただけると助かります。

2017-03-08 03:51 UTC, KeenS requested changes
1点コメントしました。ご確認下さい。

2017-03-08 03:51 UTC, KeenS commented on 1.9/ja/book/method-syntax.md
> +さて、私たちは先ほどの要求を守らせるために型システムを使いました。
> 要求を守らせるために

先に出てきた「要求」は制限したいではなくて自由を得たいという内容だったので
「要求を実現するために」
はいかがでしょうか。

2017-03-08 14:22 UTC, tatsuya6502 commented on 1.9/ja/book/method-syntax.md
> +さて、私たちは先ほどの要求を守らせるために型システムを使いました。
@KeenS コメントありがとうございます。自由を得たいということですが、その要求とはどこを指してますか？

2017-03-13 10:44 UTC, Wakamatz commented on 1.9/ja/book/method-syntax.md
> +さて、私たちは先ほどの要求を守らせるために型システムを使いました。
ここではcircleを作成するというのが要求ですから「守らせる」の方が正しいと思います。
ただ日本語的には「満たす」とした方がより自然ではないでしょうか？
いかがでしょうか？

2017-03-13 11:51 UTC, KeenS commented on 1.9/ja/book/method-syntax.md
> +さて、私たちは先ほどの要求を守らせるために型システムを使いました。
しばらく家を空けていて返信遅れました。

> ユーザが `Circle` を作成する際、関心のあるプロパティだけを指定できるようにしたいとしましょう。
> 指定がなければ `x` と `y` は `0.0` 、 `radius` は `1.0` にします。

の意図でした。「関心のあるものだけ指定したい」という要求（要件）です。

> ただ日本語的には「満たす」とした方がより自然ではないでしょうか？

その方が良いかもしれません。

2019-11-21 00:10 UTC, closed without merging