[WIP] 5.6 Concurrency
rust-lang-ja/the-rust-programming-language-ja pull request #196
Opened 2016-07-16 06:42 UTC by KeenS

2016-12-12 07:54 UTC, KeenS commented
そこそこ変更料があります。

2017-01-25 12:07 UTC, tatsuya6502 commented
CircleCI: https://circleci.com/gh/rust-lang-ja/the-rust-programming-language-ja/160

2017-01-29 04:29 UTC, tatsuya6502 requested changes
@KeenS ２点コメントしました。ご確認をお願いします。

2017-01-29 04:29 UTC, tatsuya6502 commented on 1.9/ja/book/concurrency.md
> +`Rc<T>` に対して `clone()` を呼ぶと新たな所有権を持った参照を返し、内部の参照カウント数を増やします。
細かい話ですが、reference count の訳が、「リファレンスカウント」と「参照カウント」の２つに揺れています。対訳表では「参照カウント」になっていますので、そちらに統一するのがよいかと思います。

ただ、ひょっとすると、Rc が "reference count" の頭文字であることがわかるように、あえて「リファレンスカウント」としているのでしょうか？　もしそうなら、たとえば、以下のようにするのはどうでしょうか？（さらに、"of its name" も取り入れてみました）

```
通常、この用途には `Rc<T>` を使います。これは所有権の共有を提供する参照カウントの型です。
実行時にある程度の管理コストを払って、値への参照の数をカウントします。
なので名前に参照カウント(reference count) が付いているのです。

`Rc<T>` に対して `clone()` を呼ぶと新たな所有権を持った参照を返し、内部の参照カウント数を増やします。
```

2017-01-29 04:29 UTC, tatsuya6502 commented on 1.9/ja/book/concurrency.md
> +要点は `Arc<T>` は _スレッド間_ で所有権を共有可能にする方ということです。
「方」→「型」

2017-01-30 01:18 UTC, KeenS commented on 1.9/ja/book/concurrency.md
> +`Rc<T>` に対して `clone()` を呼ぶと新たな所有権を持った参照を返し、内部の参照カウント数を増やします。
参照カウントとすべきところですね。直します。

2017-01-30 01:50 UTC, KeenS commented
指摘箇所以外にももう1つ参照カウントがリファレンスカウントになってる箇所があったので修正しました。

2017-01-30 02:42 UTC, tatsuya6502 approved these changes
@KeenS 修正ありがとうございました。レビューOKですので、マージします。

おつかれさまでした！

2017-01-30 02:43 UTC, merged