[5.5] Iterators
rust-lang-ja/the-rust-programming-language-ja pull request #216
Opened 2016-12-12 08:17 UTC by KeenS

2017-01-25 12:08 UTC, tatsuya6502 commented
CircleCI: https://circleci.com/gh/rust-lang-ja/the-rust-programming-language-ja/161

2017-01-25 12:50 UTC, tatsuya6502 requested changes
@KeenS 一点、コメントしました。ご確認をお願いいたします。

2017-01-25 12:50 UTC, tatsuya6502 commented on 1.9/ja/book/iterators.md
> +（ところで、 `0..10` のようにドット2つのレンジは左端を含み（つまり0から始まる）右端を含みません（つまり9で終わる）。数学的な書き方をすれば 「[0, 10)]」です。10まで含むレンジが欲しければ `0...10` と書きます。）
`「[0, 10)]」` ですが、`「[0, 10)」` （閉じカギ括弧なし）に修正していただけますか？

2017-01-25 13:42 UTC, KeenS commented
修正しました

2017-01-26 00:10 UTC, tatsuya6502 approved these changes

2017-01-26 00:10 UTC, tatsuya6502 commented
@KeenS ありがとうございます！　マージします。

2017-01-26 00:10 UTC, merged