4.32 Macros
rust-lang-ja/the-rust-programming-language-ja pull request #220
Opened 2016-12-12 09:00 UTC by KeenS

@tatsuya6502 レビューお願いします。

2017-01-28 08:51 UTC, tatsuya6502 commented
CircleCI: https://circleci.com/gh/rust-lang-ja/the-rust-programming-language-ja/176#artifacts

2017-01-28 09:02 UTC, tatsuya6502 requested changes
@KeenS １点だけコメントしました。ご確認をお願いします。

2017-01-28 09:02 UTC, tatsuya6502 commented on 1.9/ja/book/macros.md
> +そのようにする場合、例えば `$(I $i:ident)* E $e:exp` のように書くことができます。
細かいのですが、原文で `E $e:exp` が `E $e:expr` に修正されていますので、訳文の方でも修正をお願いします。

2017-01-30 01:20 UTC, KeenS commented on 1.9/ja/book/macros.md
> +そのようにする場合、例えば `$(I $i:ident)* E $e:exp` のように書くことができます。
気付きませんでした。ありがとうございます。

2017-01-30 02:48 UTC, tatsuya6502 approved these changes
@KeenS 修正ありがとうございました。レビューOKですので、マージします。

おつかれさまでした！

2017-01-30 02:48 UTC, merged