4.15 Patterns
rust-lang-ja/the-rust-programming-language-ja pull request #224
Opened 2016-12-12 12:32 UTC by KeenS

@tatsuya6502 
翻訳の質がそんなに良くなかったのとコメントアウトの方法が段落毎でなくてパッチを適用しづらかったので全体的に手を入れました。
diffが多くて見辛いと思いますが宜しくお願いします。

2017-01-28 08:53 UTC, tatsuya6502 commented
CircleCI: https://circleci.com/gh/rust-lang-ja/the-rust-programming-language-ja/179#artifacts

2017-01-30 10:41 UTC, tatsuya6502 commented
メモ：1.9 英語版の patterns.md
https://raw.githubusercontent.com/rust-lang/rust/1.9.0/src/doc/book/patterns.md

2017-01-30 11:05 UTC, tatsuya6502 requested changes
> 翻訳の質がそんなに良くなかったのとコメントアウトの方法が段落毎でなくてパッチを適用しづらかったので全体的に手を入れました。
> diffが多くて見辛いと思いますが宜しくお願いします。

@KeenS ありがとうございます！　全体的に良くなったと思います。念のため、diff ではなくて、英語版の 1.9 patterns.md と見比べて違いがないことを確認し、訳も全部、読みました。細かな内容で何点かコメントしましたので、ご確認をお願いします。

2017-01-30 11:05 UTC, tatsuya6502 commented on 1.6/ja/book/patterns.md
>  % パターン
1.6 のファイルが変更されてますね。このままレビューしますが、私からのコメントに対応した後、1.9 のファイルとの入れ替えをお願いします。

2017-01-30 11:05 UTC, tatsuya6502 commented on 1.6/ja/book/patterns.md
> +// Here, tuple is _not_ moved, as the String was never moved, and u32 is Copy:
この行の行頭に `#` を入れてください。

2017-01-30 11:05 UTC, tatsuya6502 commented on 1.6/ja/book/patterns.md
> +// However,
この行（`However`）の訳もお願いします。

2017-01-30 11:05 UTC, tatsuya6502 commented on 1.6/ja/book/patterns.md
>  `if` を使うことでマッチガードを導入することができます：
1.9 の変更点とは関係ないのですが、ついでに、`マッチガード` を `「マッチガード」` に変えてもらえると嬉しいです。

2017-02-23 04:45 UTC, KeenS commented on 1.6/ja/book/patterns.md
>  % パターン
ぎゃー。ごめんなさい。そのように対応します。

2017-02-23 04:58 UTC, KeenS commented
指摘点反映しました。1.6のコミットログを汚さないようにrebaseしました。

2017-02-24 02:50 UTC, tatsuya6502 approved these changes

2017-02-24 02:50 UTC, tatsuya6502 commented
修正点の反映、ありがとうございました。レビューOKですので、マージします。

2017-02-24 02:51 UTC, merged